export function generateAIReport(data) {
  return `
==============================
SellAI ENTERPRISE REPORT
==============================

Generated:
${data.date}

--------------------------------
FINANCIAL OVERVIEW
--------------------------------

Revenue:
$${data.revenue.toLocaleString()}

Profit:
$${data.profit.toLocaleString()}

Orders:
${data.orders}

Customers:
${data.customers}

Forecast:
$${data.forecast.toLocaleString()}

--------------------------------
AI INSIGHTS
--------------------------------

${data.insights.map((item, index) => `${index + 1}. ${item}`).join("\n")}

--------------------------------
AI SUMMARY
--------------------------------

The business demonstrates stable performance.

Revenue continues to grow.

Customer acquisition remains positive.

The forecast predicts continued growth next month.

AI recommends increasing investment in the highest-performing categories and maintaining inventory levels for best-selling products.

==============================
Generated by SellAI Enterprise
==============================
`;
}